### PR TITLE
add Maskable icon

### PR DESCRIPTION
**Pull request by nstringham**
this PR fixes a few small problems with the icons in the manifest and adds a maskable icon which will allow the app to look better on modern Android phones

### CODE REVIEW

**Comment by devrsi0n** [comment]
@nstringham Thanks for the contribution, could you paste a `before vs after` screenshot in the description? I don't have an Android phone to test it currently.

**Comment by nstringham** [comment]
the left is before and the right is after

the 2 screenshots are taken with 2 different icon shapes

screenshots taken on LineageOS 18.1 (unofficial) based on Android 11

Screenshot_20211129-155331_Trebuchet
Screenshot_20211129-155239_Trebuchet

**Comment by devrsi0n** [comment]
@nstringham Wow, that's impressive, I think many people will love it. Please note: I will check it in when I migrated this site to modern cloud providers.

**Comment by nstringham** [comment]
> @nstringham Wow, that's impressive, I think many people will love it.

thanks

**Comment by devrsi0n** [comment]
@nstringham  Thank you for your patient, the app should be updated.
image

**Pull request merged**
